import { DatabaseSync } from 'node:sqlite';
import crypto from 'node:crypto';
import { validateConfig, transitionMatrix } from '../lib/dei-domain.mjs';

export class SqliteStore {
  constructor(filename=':memory:'){this.db=new DatabaseSync(filename);this.db.exec('PRAGMA foreign_keys = ON;');this.migrate();}
  migrate(){this.db.exec(`
    CREATE TABLE IF NOT EXISTS activities (id TEXT PRIMARY KEY,title TEXT NOT NULL,model TEXT NOT NULL DEFAULT 'dei' CHECK (model='dei'),schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version>0),active INTEGER NOT NULL DEFAULT 0 CHECK (active IN (0,1)),config_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS activity_sessions (id TEXT PRIMARY KEY,activity_id TEXT NOT NULL REFERENCES activities(id),status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),config_snapshot_json TEXT NOT NULL,schema_version_snapshot INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at TEXT);
    CREATE UNIQUE INDEX IF NOT EXISTS one_open_session_per_activity ON activity_sessions(activity_id) WHERE status='open';
    CREATE TABLE IF NOT EXISTS dei_response_traces (id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES activity_sessions(id) ON DELETE CASCADE,participant_hash TEXT NOT NULL,initial_response INTEGER NOT NULL CHECK (initial_response BETWEEN 1 AND 5),initial_committed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,information_seen_at TEXT,revised_response INTEGER CHECK (revised_response BETWEEN 1 AND 5),revised_committed_at TEXT,completed_at TEXT,UNIQUE(session_id,participant_hash));
  `);}
  close(){this.db.close();}
  upsertActivity(activity){const config=validateConfig(activity.config);this.db.prepare(`INSERT INTO activities(id,title,model,schema_version,active,config_json,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET title=excluded.title,schema_version=excluded.schema_version,active=excluded.active,config_json=excluded.config_json,updated_at=CURRENT_TIMESTAMP`).run(activity.id,activity.title,'dei',activity.schema_version??1,activity.active?1:0,JSON.stringify(config));}
  getActivity(id,{requireActive=false}={}){const row=this.db.prepare('SELECT * FROM activities WHERE id = ?').get(id);if(!row)return null;if(requireActive&&!row.active)return null;return{...row,active:Boolean(row.active),config:JSON.parse(row.config_json)};}
  createSession(activityId){const activity=this.getActivity(activityId,{requireActive:true});if(!activity)throw new Error('activity not found or inactive');const existing=this.getOpenSession(activityId);if(existing)return existing;const id=crypto.randomUUID();this.db.prepare(`INSERT INTO activity_sessions(id,activity_id,status,config_snapshot_json,schema_version_snapshot) VALUES(?,?,?,?,?)`).run(id,activityId,'open',JSON.stringify(activity.config),activity.schema_version);return this.getSession(id);}
  getSession(id){const row=this.db.prepare('SELECT * FROM activity_sessions WHERE id = ?').get(id);return row?{...row,config_snapshot:JSON.parse(row.config_snapshot_json)}:null;}
  getOpenSession(activityId){const row=this.db.prepare(`SELECT * FROM activity_sessions WHERE activity_id=? AND status='open'`).get(activityId);return row?{...row,config_snapshot:JSON.parse(row.config_snapshot_json)}:null;}
  closeSession(sessionId){this.db.prepare(`UPDATE activity_sessions SET status='closed',closed_at=CURRENT_TIMESTAMP WHERE id=? AND status='open'`).run(sessionId);return this.getSession(sessionId);}
  commitInitial(sessionId,participantHash,response){const session=this.getSession(sessionId);if(!session||session.status!=='open')throw new Error('session is not open');this.db.prepare(`INSERT INTO dei_response_traces(id,session_id,participant_hash,initial_response) VALUES(?,?,?,?) ON CONFLICT(session_id,participant_hash) DO NOTHING`).run(crypto.randomUUID(),sessionId,participantHash,response);return this.getTrace(sessionId,participantHash);}
  markInformationSeen(sessionId,participantHash){const trace=this.getTrace(sessionId,participantHash);if(!trace)throw new Error('initial response has not been committed');this.db.prepare(`UPDATE dei_response_traces SET information_seen_at=COALESCE(information_seen_at,CURRENT_TIMESTAMP) WHERE session_id=? AND participant_hash=?`).run(sessionId,participantHash);return this.getTrace(sessionId,participantHash);}
  commitRevised(sessionId,participantHash,response){const session=this.getSession(sessionId);if(!session||session.status!=='open')throw new Error('session is not open');const trace=this.getTrace(sessionId,participantHash);if(!trace)throw new Error('initial response has not been committed');if(!trace.information_seen_at)throw new Error('information review has not been completed');this.db.prepare(`UPDATE dei_response_traces SET revised_response=COALESCE(revised_response,?),revised_committed_at=COALESCE(revised_committed_at,CURRENT_TIMESTAMP),completed_at=COALESCE(completed_at,CURRENT_TIMESTAMP) WHERE session_id=? AND participant_hash=?`).run(response,sessionId,participantHash);return this.getTrace(sessionId,participantHash);}
  getTrace(sessionId,participantHash){return this.db.prepare(`SELECT * FROM dei_response_traces WHERE session_id=? AND participant_hash=?`).get(sessionId,participantHash)??null;}
  getCounts(sessionId){const row=this.db.prepare(`SELECT COUNT(*) AS initial_count,SUM(CASE WHEN information_seen_at IS NOT NULL THEN 1 ELSE 0 END) AS reviewed_count,SUM(CASE WHEN revised_response IS NOT NULL THEN 1 ELSE 0 END) AS revised_count FROM dei_response_traces WHERE session_id=?`).get(sessionId);return{initial:Number(row.initial_count??0),reviewed:Number(row.reviewed_count??0),revised:Number(row.revised_count??0)};}
  getCompletedPairs(sessionId){return this.db.prepare(`SELECT initial_response,revised_response FROM dei_response_traces WHERE session_id=? AND revised_response IS NOT NULL ORDER BY initial_committed_at,id`).all(sessionId);}
  getResults(sessionId){return transitionMatrix(this.getCompletedPairs(sessionId));}
}
